export const Types = {
  GET_EVENTS:"GET_EVENTS",
  SHOW_ADD_EVENT_MODAL:"SHOW_ADD_EVENT_MODAL",
  HIDE_ADD_EVENT_MODAL:"HIDE_ADD_EVENT_MODAL",
  ADD_EVENTS:"ADD_EVENTS",
  EVENT_DATA:"EVENT_DATA",
  EVENT_ROW_COUNT:"EVENT_ROW_COUNT",
  UPDATE_EVENT:"UPDATE_EVENT",
  EVENT_PAGE_NUMBER:"EVENT_PAGE_NUMBER"
};
