export const Types = {
    SET_SIGN_IN_MESSAGE: "SET_SIGN_IN_MESSAGE",
    LOG_IN_USER: "LOG_IN_USER",
    REDIRECT:"REDIRECT",
    GET_USER_LIST:"GET_USER_LIST",
    USER_INFO:"USER_INFO",
    TOTAL_COUNT:"TOTAL_COUNT",
    SHOW_UPDATE_MODAL:"SHOW_UPDATE_MODAL",
    HIDE_UPDATE_MODAL:"HIDE_UPDATE_MODAL",
    RESET_PASSWORD:"RESET_PASSWORD",
    IS_TOKEN_VALID:"IS_TOKEN_VALID",
    GET_RECENT_ACTIVITY:"GET_RECENT_ACTIVITY",
    TOTAL_RECENT_COUNT:"TOTAL_RECENT_COUNT",
    RECENT_ACTIVITY_INFO:"RECENT_ACTIVITY_INFO",
    GET_EVENTS_PER_USER:"GET_EVENTS_PER_USER",
    STORE_USER_INFO:"STORE_USER_INFO",
    GET_USER_INFO:"GET_USER_INFO",
    RESET_PASSWORD_TOKEN:"RESET_PASSWORD_TOKEN",
    RESET_PASSWORD_STATUS:"RESET_PASSWORD_STATUS",
    LOGIN_STATUS:"LOGIN_STATUS",
    DEFAULT_STATUS:"DEFAULT_STATUS",
    SET_SIGNUP_MESSAGE:"SET_SIGNUP_MESSAGE"
  };
  
